spring.application.name=worker

spring.datasource.url=jdbc:postgresql://localhost:5432/monitoring_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.flyway.enabled=false

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false