apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1

  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      containers:
        - name: api
          image: service-monitoring-api:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: service-monitoring-config

            - secretRef:
                name: service-monitoring-secret

---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api

  ports:
    - port: 8080
      targetPort: 8080